name: Artifact demo

on: push

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
    -name: Checkout repository
     uses: actions/checkout@v4
     
    -name: Create file
     run: |
      mkdir temp
      echo "ganesh" > temp/ganesh.html

    -name: Upload artifact
     uses: actions/upload-artifact@v4
     with:
       name: files
       path: temp/
